import { ShortcutKeys } from '@app/classes/enums/draw-enums';

export const SHORTCUTS_TABLE: string[] = [
    ShortcutKeys.PENCIL,
    ShortcutKeys.SPRAY,
    ShortcutKeys.RECTANGLE,
    ShortcutKeys.ELLIPSE,
    ShortcutKeys.LINE,
    ShortcutKeys.BUCKET,
    ShortcutKeys.ERASER,
    ShortcutKeys.EYE_DROPPER,
    ShortcutKeys.RECTANGLE_SELECTION,
    ShortcutKeys.ELLIPSE_SELECTION,
    ShortcutKeys.TEXT,
    ShortcutKeys.STAMP,
    ShortcutKeys.POLYGON,
    ShortcutKeys.LASSO,
    ShortcutKeys.NEW_DRAWING,
    ShortcutKeys.CARROUSEL,
    ShortcutKeys.SAVE,
    ShortcutKeys.EXPORT_DRAWING,
    ShortcutKeys.SELECT_ALL,
    ShortcutKeys.UNDO,
    ShortcutKeys.REDO,
    ShortcutKeys.GRID,
    ShortcutKeys.PLUS,
    ShortcutKeys.MINUS,
    ShortcutKeys.MAGNETISM,
    ShortcutKeys.COPY,
    ShortcutKeys.PASTE,
    ShortcutKeys.CUT,
];
